using System;
using Forays;
namespace Forays{
	public enum TileType{WALL,FLOOR,DOOR_O,DOOR_C,STAIRS,CHEST};
	public enum ActorType{PLAYER,RAT,GOBLIN,LARGE_BAT,SHAMBLING_SCARECROW,SKELETON,GOBLIN_ARCHER,WOLF,FROSTLING,GOBLIN_SHAMAN,ZOMBIE,DIRE_RAT,ROBED_ZEALOT,WORG,CARRION_CRAWLER,OGRE,PHASE_SPIDER,STONE_GOLEM,ORC_WARMAGE,LASHER_FUNGUS,CORPSETOWER_BEHEMOTH,FIRE_DRAKE};
	public enum AttrType{UNDEAD,CONSTRUCT,ENHANCED_TORCH,MAGICAL_BLOOD,KEEN_EYES,TOUGH,LOW_LIGHT_VISION,DARKVISION,REGENERATING,STUNNED,PARALYZED,POISONED,IMMOBILIZED,ON_FIRE,CATCHING_FIRE,DETECTING_MONSTERS,FIRE_HIT,COLD_HIT,POISON_HIT,PARALYSIS_HIT,RESIST_SLASH,RESIST_BASH,RESIST_FIRE,RESIST_COLD,RESIST_ELECTRICITY,IMMUNE_FIRE,IMMUNE_COLD,IMMUNE_ARROWS,GLOBAL_FAIL_RATE,COOLDOWN_1,COOLDOWN_2,BLESSED,HOLY_SHIELDED,SPORE_BURST,RESTING,STUDENTS_LUCK_USED,DEFENSIVE_STANCE,DRIVE_BACK_ON,TUMBLING,DANGER_SENSE_ON,WAR_SHOUTED,BONUS_COMBAT,BONUS_DEFENSE,BONUS_MAGIC,BONUS_SPIRIT,BONUS_STEALTH,HUMANOID_INTELLIGENCE,INVULNERABLE,BOSS_MONSTER,NUM_ATTRS,NO_ATTR};
	public enum EffectType{HEALING,REGENERATION,CURE_POISON,RESISTANCE,CLARITY,PHASING,TELEPORTATION,PASSAGE,DETECT_MONSTERS,MAGIC_MAP,LIGHT,WIZARDS_LIGHT,FLAME,ICE,LIGHTNING,BANDAGE,NO_EFFECT};
	public enum SpellType{SHINE,MAGIC_MISSILE,DETECT_MONSTERS,FORCE_PALM,BLINK,IMMOLATE,ICY_BLAST,BURNING_HANDS,FREEZE,SONIC_BOOM,ARC_LIGHTNING,PLACEHOLDER,SHOCK,SHADOWSIGHT,RETREAT,FIREBALL,PASSAGE,FORCE_BEAM,DISINTEGRATE,BLIZZARD,BLESS,MINOR_HEAL,HOLY_SHIELD,NUM_SPELLS,NO_SPELL};
	public enum SkillType{COMBAT,DEFENSE,MAGIC,SPIRIT,STEALTH,NUM_SKILLS,NO_SKILL};
	public enum FeatType{QUICK_DRAW,SPIN_ATTACK,LUNGE,DRIVE_BACK,SILENT_CHAINMAIL,ARMORED_MAGE,FULL_DEFENSE,TUMBLE,MASTERS_EDGE,STUDENTS_LUCK,ARCANE_HEALING,FORCE_OF_WILL,WAR_SHOUT,ENDURING_SOUL,FEEL_NO_PAIN,FOCUSED_RAGE,CORNER_LOOK,DISARM_TRAP,NECK_SNAP,DANGER_SENSE,NUM_FEATS,NO_FEAT};
	public enum WeaponType{SWORD,MACE,DAGGER,STAFF,BOW,FLAMEBRAND,MACE_OF_FORCE,VENOMOUS_DAGGER,STAFF_OF_MAGIC,HOLY_LONGBOW,NUM_WEAPONS,NO_WEAPON};
	public enum ArmorType{LEATHER,CHAINMAIL,FULL_PLATE,ELVEN_LEATHER,CHAINMAIL_OF_ARCANA,FULL_PLATE_OF_RESISTANCE,NUM_ARMORS,NO_ARMOR};
	public enum MagicItemType{PENDANT_OF_LIFE,RING_OF_RESISTANCE,RING_OF_PROTECTION,CLOAK_OF_DISAPPEARANCE,NUM_MAGIC_ITEMS,NO_MAGIC_ITEM};
	public enum DamageType{NORMAL,MAGIC,FIRE,COLD,ELECTRIC,POISON,HEAL};
	public enum EventType{ANY_EVENT,MOVE,REMOVE_ATTR,BOSS_ARRIVE};
	public enum OptionType{LAST_TARGET,VI_KEYS,OPEN_CHESTS};
	public class Game{
		public Map M;
		public Queue Q;
		public Buffer B;
		public Actor player;
		
		static void Main(string[] args){
			Console.TreatControlCAsInput = true;
			Console.BufferHeight = Global.SCREEN_H; //25
			//Console.CursorSize = 100;
			Game game = new Game();
			game.player = new Actor(ActorType.PLAYER,"you",'@',ConsoleColor.White,100,100,0,1,0);
			game.M = new Map(game);
			game.B = new Buffer(game);
			game.Q = new Queue(game);
			PhysicalObject.M = game.M;
			Actor.M = game.M;
			Actor.Q = game.Q;
			Actor.B = game.B;
			Actor.player = game.player;
			Item.M = game.M;
			Item.Q = game.Q; //this part is so ugly
			Item.B = game.B;
			Item.player = game.player;
			Event.Q = game.Q;
			Event.B = game.B; //i want to change it somehow
			Tile.M = game.M;
			Tile.B = game.B;
			Tile.player = game.player;
			//game.M.InitLevel();
			game.M.LoadLevel("map.txt");
			game.player.Q0();
			game.player.Move(10,20); //this is why the voodoo was needed before: the player must be moved onto the map *before*
			game.player.UpdateRadius(0,6,true); //gaining a light radius.
			while(true){ game.Q.Pop(); }
		}
	}
}
